game.addGameOverTip(_T("TIP_1", "Managers can speed up engine and game development."))
game.addGameOverTip(_T("TIP_2", "It's better to have specialized employees of specific roles instead of generalized employees."))
game.addGameOverTip(_T("TIP_3", "Having more employees allows everyone to finish their tasks quicker, because they can help each other."))
game.addGameOverTip(_T("TIP_4", "Advertisement is most effective when a game is still in development."))
game.addGameOverTip(_T("TIP_5", "Hype wears off over time, perform any kind of marketing to stall its drop."))
game.addGameOverTip(_T("TIP_6", "Employees idling? Enable auto-practice in the 'Office preferences' menu."))
game.addGameOverTip(_T("TIP_7", "Placing food-related objects can slow the Drive drop of your employees."))
game.addGameOverTip(_T("TIP_8", "Make sure to test your game or hire a QA company to do it for you."))
game.addGameOverTip(_T("TIP_9", "A great game with no hype surrounding it is sure to be a failure in terms of sales."))
game.addGameOverTip(_T("TIP_10", "Reputation is hard to attain and easy to lose. Think twice before acting."))
game.addGameOverTip(_T("TIP_11", "Go on team building activities to temporarily boost employee Drive levels."))
game.addGameOverTip(_T("TIP_12", "Denying raise and vacations requests will leave your employees frustrated, which can lead to them leaving to work elsewhere."))
