interactionRestrictor:addUnlockCallback("contract_work", function()
	contractWork:unlock()
end)
interactionRestrictor:addRestrictCallback("contract_work", function()
	contractWork:lock()
end)
interactionRestrictor:addUnlockCallback("trends", function()
	trends:unlock()
end)
interactionRestrictor:addRestrictCallback("trends", function()
	trends:lock()
end)
interactionRestrictor:addUnlockCallback("engine_licensing", function()
	engineLicensing:unlock()
end)
interactionRestrictor:addRestrictCallback("engine_licensing", function()
	engineLicensing:lock()
end)
interactionRestrictor:addUnlockCallback("game_convention", function()
	gameConventions:unlock()
end)
interactionRestrictor:addRestrictCallback("game_convention", function()
	gameConventions:lock()
end)
interactionRestrictor:addUnlockCallback("rival_game_companies", function()
	rivalGameCompanies:unlock()
end)
interactionRestrictor:addRestrictCallback("rival_game_companies", function()
	rivalGameCompanies:lock()
end)
interactionRestrictor:addUnlockCallback("generic_game_interaction", function()
	gameAwards:unlock()
end)
interactionRestrictor:addRestrictCallback("generic_game_interaction", function()
	gameAwards:lock()
end)
